name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install flake8 pytest pep8-naming
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 --ignore "N801, E203, E266, E501, W503, F812, F401, F841, E741, N803, N802, N806" minitorch/ tests/ project/
    - name: Test with pytest
      run: |
        echo "Basic functionalities tests"
        pytest tests -x -m basic_math_ops
        pytest tests -x -m basic_math_properties
        pytest tests -x -m high_order_fn
        pytest tests -x -m test_module_simple
        echo "Autodiff tests"
        pytest tests -x -m scalar
        pytest tests -x -m derivative
        pytest tests -x -m chain_rule
        pytest tests -x -m backprop
        echo "Tensor tests"
        pytest tests -x -m tensor_data
        pytest tests -x -m tensor_fn
        echo "CPU and CUDA operators tests"
        pytest tests -x -m fast_ops
        pytest tests -x -m cuda_ops
        echo "NN tests"
        pytest tests -x -m fast_conv
        pytest tests -x -m nn_layers
        pytest tests -x -m cuda_conv
